# Etapa 1: Construcción del contenedor base para el frontend
FROM node:18 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del frontend al contenedor
COPY ./frontend /app

# Instalar las dependencias y construir el proyecto
RUN npm install && npm run build

# Etapa 2: Servir el frontend usando un servidor estático
FROM nginx:alpine

# Copiar los archivos construidos al servidor nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer el puerto (usualmente el 80 para HTTP)
EXPOSE 80