services:
  voicerag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - YOUR_ENV_VAR=default_value
    volumes:
      - ./app/backend:/app/backend
      - ./app/frontend:/app/frontend