# Etapa 1: Construcción del contenedor base para el backend
FROM python:3.11-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del backend al contenedor
COPY ./backend /app

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto en el que corre el backend (suponiendo que corre en el 8000)
EXPOSE 8000

# Establecer el comando para ejecutar la aplicación
CMD ["python", "app.py"]
