name: Trigger auto deployment for cvenvoicerag

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cvenvoicerag-AutoDeployTrigger-c3b77812-5565-485d-a1c4-83ddff4afa17.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CVENVOICERAG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CVENVOICERAG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CVENVOICERAG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CVENVOICERAG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CVENVOICERAG_REGISTRY_PASSWORD }}
          containerAppName: cvenvoicerag
          resourceGroup: CVEN-JOSE-RG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


